### ISSUE TITLE
Bot strings language localization

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/plugin-template#19]
Original comment: https://github.com/ubiquibot/command-start-stop/pull/25#discussion_r1736233348

There may be [cases](https://github.com/ubiquibot/command-start-stop/issues/22) when partner would need to customize the plugin's text response to some commands. 

Possible use cases:
- different text messages for different business logic flows
- translation to other languages

It could be useful to keep a separate `json` file of used strings in the plugin repository. This way plugin developers would host `json` file in the plugin's repo while partners would be able to customize the whole "text strings" file without cluttering the config too much.

Example config with a new param `customStringsUrl`:
```
- plugin: http://localhost:4000
  name: start-stop
  id: start-stop-command
  description: "Allows a user to start/stop a task without negative XP impact"
  command: "\/start|\/stop"
  example: "/start" # or "/stop"
  with:
    reviewDelayTolerance: "3 Days"
    taskStaleTimeoutDuration: "30 Days"
    maxConcurrentTasks: 3
    startRequiresWallet: true
    ## ...
    ## ...
    ## NEWLY ADDED CONFIG PARAM
    customStringsUrl: https://raw.githubusercontent.com/dev/new-pugin/development/strings.json
```

So as a part of this issue we should add a basic plugin config and an example usage of the `customStringsUrl` param so that future plugin developers could fork this repo and use configurable text messages instead of hardcoding them in the code.
