### ISSUE TITLE
Update configuration action

### ISSUE THREAD

**Issue by whilefoo** [ubiquibot/plugin-template#29]
The `update-configuration.yml` doesn't apply formatting according to the prettier configuration

Also I think it would be better to make this a [custom action](https://docs.github.com/en/actions/sharing-automations/creating-actions/about-custom-actions) which would prevent duplication, we can use Typescript instead of writing code in the YML and allow us to change it without having to apply changes to every repo that forks plugin-template.

The only question is how to specify where the schema is located in the code, it could be something like this:
```yml
- name: update configuration
  uses: ubiquity-os/update-configuration
  with:
    filepath: './src/types'
    typeboxSchemaName: 'pluginSettingsSchema'
```
and then we can dynamically import it!

In the future we could also support different schema libraries (zod, joi...)

@0x4007 rfc
